#!/bin/sh
# Loop through modified .aseprite files, use Aseprite's command line interface to save modified files as pngs.
set -m
export aseprite=$aseprite
MODIFIED_FILES=$(git diff origin/master HEAD --name-only) # Ideally this would filter to *.aseprite files
for file in $MODIFIED_FILES
do
	if [[ $file == *.aseprite ]]
	then
		"$aseprite" -b "${file}" --save-as "${file/.aseprite/.png}"
	fi
done
# Add newly converted pngs to the commit
if [ -e .commit ]
    then
    rm .commit
    git add .
    git commit --amend -C HEAD --no-verify
fi
exit 0